spring:
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/code?useunicode=true&characterEncoding=utf8&serverTimezone=UTC
   username: root
   password: 123456